[package]
name = "activities"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
selenium-rs = "0.1"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.26"
